name: build-images-action

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build_ipa_downloader:
    name: build ipa downloader image
    if: github.repository == 'metal3-io/ironic-ipa-downloader'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'ironic-ipa-downloader'
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
